org.gradle.jvmargs = -Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.18.4
loom_version=1.13-SNAPSHOT


# Mod Properties
mod_name = PetPhraseX
mod_version = 1.4.1
maven_group = committee.nova
target_java_version = 21
archives_base_name=PetPhraseX-Fabric
