# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4096m
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true

minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT


# Mod Properties
mod_name = PetPhraseX
mod_version = 1.2.1
maven_group = committee.nova
target_java_version = 21
archives_base_name=PetPhraseX-Fabric
