org.gradle.jvmargs = -Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true

minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT


# Mod Properties
mod_name = PetPhraseX
mod_version = 1.2.2
maven_group = committee.nova
target_java_version = 21
archives_base_name=PetPhraseX-Fabric
